# Generated by Django 4.0.9 on 2023-02-16 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pods', '0003_service_remove_pod_slot_pod_amount_pod_holidays_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateTimeField()),
                ('date_end', models.DateTimeField()),
                ('email', models.EmailField(max_length=254)),
                ('token', models.TextField()),
                ('expired', models.DateTimeField()),
                ('pod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pods.pod')),
            ],
        ),
    ]
